#!/usr/bin/python
import os
import sys

file1=open('exim_mainlog2', 'r')
MakeList=file1.read().split('T=')
file1.close()
startLoc = "T="
endLoc = "for"
for i in range (len(MakeList)):
  myString=MakeList[i]
  mySubString=myString[myString.find("T=")+1:myString.find(" for")]
  line = mySubString.strip()
  if  line.startswith('"'):
    print(line)
