#!/opt/rh/rh-python36/root/usr/bin/python
import re
import os
import subprocess
from subprocess import Popen, PIPE
username = input("Enter the username:")
password = input("Enter the password:")
flag = 0
while True:
	if (len(password)< 8):
		flag  = -1
		break
	elif not re.search("[a-z]", password):
		flag = -1
		break
	elif not re.search("[A-Z]", password):
		flag = -1
		break
	elif not re.search("[_@$]", password):
		flag = -1
		break
	elif not re.search("[0-9]", password):
		flag = -1
		break
	elif re.search("\s", password):
		flag = -1
		break
	else:
		flag = 0
		print ("Password validation sucessfull:", password)
		break
if flag == -1:
	print ("Password is invalid:", password)
