#!/usr/local/sbin/python
import string
from random import *
import os
import sys
import subprocess
from prettytable import PrettyTable

tbl1 = PrettyTable(['Username', 'Password'])
passfile = open('/etc/passwd', 'r')
passlist = passfile.readlines()
pass_dict = {}
for i in range (len(passlist)):
  pass_string1=passlist[i]
  pass_string2=pass_string1.split(':')
  pass_dict.setdefault(pass_string2[-1], []).append(pass_string2[0])
result = pass_dict.get('/bin/bash\n')
print ("List of users with shell access and updated login credentials: ")
for i in range(len(result)):
  uname = result[i] 
  pass_chars = string.ascii_letters + string.punctuation + string.digits
  gen_pass = "".join(choice(pass_chars) for x in range(randint(8,16)))
  proc1=subprocess.Popen(["echo", "%s" %(gen_pass)],stdout=subprocess.PIPE)
  proc2=subprocess.Popen(["passwd", "--stdin", "%s" %(uname)],stdin=proc1.stdout,stdout=subprocess.PIPE)
  tbl1.add_row(['%s' %(uname), '%s' %(gen_pass)])
print(tbl1)
