#!/usr/bin/python
import os
import sys
import string
passfile=open('domainlist.txt', 'r')
PassList=passfile.readlines()
passfile.close()
my_domains = {}
for i in range (len(PassList)):
  myString=PassList[i]
  SubString=myString.split(':')
  my_domains.setdefault(SubString[0], []).append(SubString[-1])
#print my_domains

domfile=open('domainlist1.txt', 'r')
DomList=domfile.readlines()
domfile.close()

notmy_domain=None
for i in range (len(DomList)):
  item=DomList[i].split(':')[0]
  dom_exist=my_domains.get(item)
  if (dom_exist == notmy_domain) :
    print item
